name: terraform-fmt-name

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-fmt-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform fmt -check -diff -recursive
